---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: dux
description: sdzfbbbbb
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest
modules:
  - type: files
    files:
      - source: system
        destination: / 
        
  - type: dnf
    repos:
      cleanup: false
      keys:
        - https://repo.cider.sh/RPM-GPG-KEY
      files:
        - cider.repo
      copr:
        - brycensranch/gpu-screen-recorder-git
        - atim/starship
        - ilyaz/LACT
        - lionheartp/Hyprland
        - sneexy/zen-browser
        - erikreider/SwayNotificationCenter
        - avengemedia/dms-git
        - avengemedia/danklinux
        - yalter/niri-git
        - scrollwm/packages 
    group-install:
      with-optional: true
      packages:
        - virtualization
    install:
      install-weak-deps: true
      skip-unavailable: true
      packages:
        - slurp
        - grim
        - Cider
        - libseat
        - google-noto-fonts
        - google-noto-sans-fonts
        - google-noto-sans-cjk-fonts
        - repo: copr:copr.fedorainfracloud.org:brycensranch:gpu-screen-recorder-git
          packages:
            - gpu-screen-recorder-ui
        - gtk4-layer-shell
        - mpv
        - mpv-libs
        - dms
        - kernel-modules-extra
        - playerctl
        - steam
        - repo: copr:copr.fedorainfracloud.org:yalter:niri-git
          packages:
            - niri
        - xwayland-satellite
        - btop
        - qt6ct
        - gvfs-smb
        - gparted
        - dms-greeter
        - syncthing
        - fastfetch
        - starship
        - lact
        - dbus-x11
        - zen-browser
        - adw-gtk3-theme
        - uxplay
        - rclone
        - scroll
        - xdg-desktop-portal-wlr
        - wl-clipboard
        - nautilus
        - xdg-desktop-portal-gnome
        - qt6ct
        - matugen
        - helix
        - ghostty
        - fish
        - apcupsd
        - nut
        - realtime-setup
        - hyprland-git
        - hyprland-guiutils
        - mangohud
        - xdg-desktop-portal-hyprland
        - freerdp
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: fonts
    fonts:
      nerd-fonts:
        - CascadiaCode
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
        - Iosevka
      google-fonts:
        - Noto Sans
        - Roboto
        - Open Sans

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

