---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: c
# description will be included in the image's metadata
description: sdzfbbbbb

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # latest is also supported if you want new updates ASAP
modules:
  - type: files
    files:
      - source: system
        destination: / 

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/pyra/discord/repo/fedora-%OS_VERSION%/pyra-discord-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ilyaz/LACT/repo/fedora-%OS_VERSION%/ilyaz-LACT-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-%OS_VERSION%/ryanabx-cosmic-epoch-fedora-%OS_VERSION%.repo
    install:
      - discord
      - gvfs-smb
      - rofi-wayland
      - kitty
      - hyprpaper
      - playerctl
      - neovim
      - btop
      - jq
      - qt6ct
      - hyprsunset
      - adw-gtk3-theme
      - hyprpicker
      - xdg-desktop-portal-hyprland
      - hyprcursor
      - hyprland-qtutils
      - hyprlock
      - hypridle
      - hyprland-git
      - mate-polkit
      - micro
      - upower
      - libgtop2
      - grimblast
      - nodejs
      - brightnessctl
      - npm
      - glfw
      - mpv
      - mpv-libs
      - libGLEW
      - nwg-look
      - syncthing
      - fastfetch
      - uwsm
      - nautilus
      - starship
      - hyprpanel
      - lact
      - hyprshot
      - cosmic-desktop
    remove:
       - firefox
       - firefox-langpacks
       
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - net.nokyan.Resources
        - com.github.tchx84.Flatseal
    user: {}

  - type: fonts
    fonts:
      nerd-fonts:
        - CascadiaCode
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Noto Sans
        - Roboto
        - Open Sans

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

