---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: c
# description will be included in the image's metadata
description: sdzfbbbbb

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/cosmic
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/pabrahamsson/hyprpanel/repo/fedora-%OS_VERSION%/pabrahamsson-hyprpanel-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/sneexy/zen-browser/repo/fedora-%OS_VERSION%/sneexy-zen-browser-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/brycensranch/gpu-screen-recorder-git/repo/fedora-%OS_VERSION%/brycensranch-gpu-screen-recorder-git-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/astal/repo/fedora-%OS_VERSION%/solopasha-astal-fedora-%OS_VERSION%.repo
    install:
      - nautilus
      - zsh
      - zsh-autosuggestions
      - rofi-wayland
      - obs-studio
      - kitty
      - hyprpaper
      - blueman
      - playerctl
      - mpv
      - neovim
      - btop
      - zen-browser
      - jq
      - qt6ct
      - hyprsunset
      - adw-gtk3-theme
      - hyprpicker
      - hyprshot
      - xdg-desktop-portal-hyprland
      - hyprcursor
      - hyprland-qtutils
      - gpu-screen-recorder
      - hyprlock
      - hypridle
      - zen-browser
      - hyprpanel
      - hyprland
      - micro
      - starship
    remove:
      - power-profiles-daemon
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - ru.linux_gaming.PortProton
        - net.rpcs3.RPCS3
        - net.pcsx2.PCSX2
        - net.nokyan.Resources
        - com.github.tchx84.Flatseal
        - com.plexamp.Plexamp
        - md.obsidian.Obsidian
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {}

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Noto Sans
        - Roboto
        - Open Sans
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

