---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: c
description: sdzfbbbbb
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42
modules:
  - type: files
    files:
      - source: system
        destination: / 
        
  - type: dnf
    repos:
      cleanup: true
      keys:
        - https://repo.cider.sh/RPM-GPG-KEY
      files:
        - cider.repo
        - https://negativo17.org/repos/fedora-steam.repo
      nonfree: negativo17
      copr:
        - atim/starship
        - ilyaz/LACT
        - faugus/faugus-launcher
        - yalter/niri-git
        - garzj/discord-canary
        - solopasha/hyprland
        - sneexy/zen-browser
    optfix:
      - zen
    install:
      skip-unavailable: false
      packages:
        - repo: copr:copr.fedorainfracloud.org:yalter:niri-git
          packages:
            - niri
        - steam
        - waybar
        - discord-canary
        - steam
        - kernel-modules-extra
        - rofi-wayland
        - kitty
        - playerctl
        - neovim
        - btop
        - qt6ct
        - mate-polkit
        - micro
        - nodejs
        - brightnessctl
        - npm
        - glfw
        - mpv
        - mpv-libs
        - libGLEW
        - nwg-look
        - syncthing
        - fastfetch
        - uwsm
        - starship
        - lact
        - faugus-launcher
        - dbus-x11
        - zen-browser
    remove:
      packages:
        - firefox
        - firefox-langpacks
       
  - type: default-flatpaks
    configurations:
    - notify: false
      scope: system
      install:
        - net.nokyan.Resources
        - com.github.tchx84.Flatseal

  - type: fonts
    fonts:
      nerd-fonts:
        - CascadiaCode
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Noto Sans
        - Roboto
        - Open Sans

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

