---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: dux
description: sdzfbbbbb
base-image: ghcr.io/ublue-os/bazzite-dx-gnome
image-version: 42
modules:
  - type: files
    files:
      - source: system
        destination: / 
        
  - type: dnf
    repos:
      cleanup: false
      keys:
        - https://repo.cider.sh/RPM-GPG-KEY
      files:
        - cider.repo
        - https://negativo17.org/repos/fedora-steam.repo
      nonfree: negativo17
      copr:
        - brycensranch/gpu-screen-recorder-git
        - atim/starship
        - ilyaz/LACT
        - yalter/niri-git
        - solopasha/hyprland
        - sneexy/zen-browser
        - errornointernet/quickshell
        - alternateved/cliphist
        - heus-sueh/packages
        - scottames/ghostty
        - erikreider/SwayNotificationCenter
    optfix:
      - zen
    group-install:
      with-optional: true
      packages:
        - virtualization
    install:
      skip-unavailable: true
      packages:
        - Cider
        - libseat
        - google-noto-fonts
        - google-noto-sans-fonts
        - google-noto-sans-cjk-fonts
        - repo: copr:copr.fedorainfracloud.org:brycensranch:gpu-screen-recorder-git
          packages:
            - gpu-screen-recorder-ui
        - gtk4-layer-shell
        - waybar
        - mpv
        - mpv-libs
        - kernel-modules-extra
        - playerctl
        - steam
        - repo: copr:copr.fedorainfracloud.org:yalter:niri-git
          packages:
            - niri
        - btop
        - qt6ct
        - mate-polkit
        - micro
        - nodejs
        - brightnessctl
        - npm
        - glfw
        - libGLEW
        - nwg-look
        - syncthing
        - fastfetch
        - xwayland-satellite
        - uwsm
        - starship
        - lact
        - dbus-x11
        - zen-browser
        - nwg-look
        - hyprlock
        - swaybg
        - mate-polkit
        - uxplay
        - quickshell-git
        - cava 
        - wl-clipboard 
        - ddcutil 
        - brightnessctl 
        - qt5ct 
        - qt6ct
        - cliphist
        - matugen
        - helix
        - input-remapper
        - gammastep
        - ghostty
        - fish
        - apcupsd
        - nut
        - realtime-setup
        - hyprshot
        - hyprland-git
        - mangohud
        - xdg-desktop-portal-hyprland
        - flameshot
        - meson
        - cmake
        - udis86
        - freerdp
        - hyprland-plugins-git
        - hyprsunset
    remove:
      packages:
        - firefox
        - firefox-langpacks
       
  - type: default-flatpaks
    configurations:
    - notify: false
      scope: system
      install:
        - net.nokyan.Resources
        - com.github.tchx84.Flatseal

  - type: fonts
    fonts:
      nerd-fonts:
        - CascadiaCode
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
        - Iosevka
      google-fonts:
        - Noto Sans
        - Roboto
        - Open Sans

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

